export const FETCH_MOVIES_API_CONFIG = "FETCH_MOVIES_API_CONFIG";
export const SET_MOVIES_SEARCH_CONFIG = "SET_MOVIES_SEARCH_CONFIG";
export const SET_FILTER_STATE = "SET_FILTER_STATE";
export const SET_DETAIL_STATE = "SET_DETAIL_STATE";
export const SET_RESULT_STATE = "SET_RESULT_STATE";
