export const FETCH_MOVIES_API_CONFIG = "FETCH_MOVIES_API_CONFIG";
export const SET_MOVIES_SEARCH_CONFIG = "SET_MOVIES_SEARCH_CONFIG";
export const FETCH_MOVIE_DATA = "FETCH_MOVIE_DATA";
export const REMOVE_MOVIE_DATA = "REMOVE_MOVIE_DATA";
